name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build conda package
        uses: BEFH/anaconda-publish@v1.5.1
        id: conda-build
        with:
          subDir: 'recipe'
          channels: 'conda-forge -c bioconda'
          publish: false
          test_all: true
          convert_win: false
          convert_osx: false
